### ISSUE TITLE
Comprehensive robustness enhancement

### ISSUE THREAD

**Issue by ailisp** [near/rainbow-bridge#258]
Here is a tracker of know robustness issue found in tests. Fix them as part of other PRs when they occur:
- [x] near-api-js query rpc timeout: https://buildkite.com/nearprotocol/nearcore/builds/2930#a5b21a48-d73f-40f3-ba4a-e3463f4c5110, fix in #254 
- [x] web3 nonce tracking error, unavoidable based on https://ethereum.stackexchange.com/questions/2527/is-there-a-way-to-find-an-accounts-current-transaction-nonce, fix by retry on higher nonce when it's failed due to nonce, in #254, 
- [ ] to fully avoid it need to replace all eth contract call with the wrapped RobustWeb3.callContract and replace all near-api-js query rpc to wrapped version, which isn't done yet.
- [x] near-watch dog didn't start: https://buildkite.com/nearprotocol/rainbow-bridge/builds/558#d42d8bde-0ecc-484b-a924-e9fd0acc4e87 practically it's not an issue but this is annoying on ci. Fixed in #273  
- [x] transfer-eth-erc20-from near uses a unwrapped version of nearcontract function call which didn't retry on timeout: https://buildkite.com/nearprotocol/rainbow-bridge/builds/586#f88f8696-8dd0-4a3c-8f48-244acc510261
Should be replaced with wrapped version (note it's not a borshContract as it's serialized in json)
- [ ] reach to near rpc failure not handled: https://buildkite.com/nearprotocol/rainbow-bridge/builds/672#dbf28908-6de8-438e-81e5-ab4ee36856b8

**Comment by nearmax** [comment]
Thank you for creating this issue and owning the product.

**Comment by ailisp** [comment]
@nearmax What was the way we used to ensure pm2 is started? It didn't happen for a while, but happens yesterday, and cause some e2e test fail,
this start near-watchdog didn't start without error (see pm2 list after it): https://buildkite.com/nearprotocol/rainbow-bridge/builds/560#e898c53a-ce75-4f30-9494-c6a3f41bfa24
this https://buildkite.com/nearprotocol/rainbow-bridge/builds/558#9bba6cf9-b6d7-47f4-aa24-c3116e697b63 ganache didn't start without error

**Comment by djsatok** [comment]
> reach to near rpc failure not handled: https://buildkite.com/nearprotocol/rainbow-bridge/builds/672#dbf28908-6de8-438e-81e5-ab4ee36856b8
This is outdated

**Comment by djsatok** [comment]
Closed in favour of the future major rewriting of the code in TypeScript
