### ISSUE TITLE
Bridge repos major update

### ISSUE THREAD

**Issue by Kouprin** [near/rainbow-bridge#372]
According to the document (https://docs.google.com/document/d/1b1MH0WSR3eHLow7iJ4qlcDJy207Kgrfdls7ZG3AB2ak), we want to update our repos architecture.

The steps are the following:
- [x] Put everything related to the Bridge system to this repo (rainbow-bridge-cli); disable CI if necessary (https://github.com/near/rainbow-bridge-cli/issues/373);
- [x] Sort the components as described in the document above;
- [x] Propose the names for the repos and Bridge components and basic description of them in 2-3 sentences (https://github.com/near/rainbow-bridge-cli/issues/374);
- [x] Publish on npm all components;
- [x] Enable linter (done in https://github.com/near/rainbow-bridge/pull/403);
- [ ] Fix dependabot alerts;
- [ ] Mock the token connector for the CI (https://github.com/near/rainbow-bridge-cli/issues/375);
- [ ] Enable CI if disabled and mark with Xs "unblock development" tasks here: https://github.com/near/rainbow-bridge-cli/issues/357;
- [ ] Rewrite config to connect to the Bridge easily (https://github.com/near/rainbow-bridge-cli/issues/344);
- [ ] Extract CLI which makes sense to Bridge developers (https://github.com/near/rainbow-bridge-cli/issues/381);
- [ ] Prepare well-written component description (https://github.com/near/rainbow-bridge-cli/issues/376);
- [ ] Prepare the manual for onboarding Bridge developers and describing how to develop under current architecture (https://github.com/near/rainbow-bridge-cli/issues/377).

**Comment by djsatok** [comment]
Outdated
